
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gardenlet
  namespace: yake
spec:
  interval: 1m
  targetNamespace: garden
  dependsOn:
    - name: gardenlet-config
    - name: gardenlet-bootstrap
  chart:
    spec:
      chart: gardenlet
      version: 1.99.1
      sourceRef:
        kind: HelmRepository
        name: gardener-community-charts
        namespace: yake
      interval: 1m
  install:
    remediation:
      retries: 3
    createNamespace: true
  values:
    runtime:
      enabled: true
    utils-templates:
      enabled: true
  valuesFrom:
    - kind: Secret
      name: gardenlet-yake-values
      optional: false
    - kind: Secret
      name: gardenlet-values
      optional: false
