{{- define "garden.domain" -}}
{{- (print "api." (first (lookup "operator.gardener.cloud/v1alpha1" "Garden" "" .Values.garden.name ).spec.virtualCluster.dns.domains)) }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: gardenlet-yake-values
  namespace: yake
type: Opaque
stringData:
  values.yaml: |
    config:
      gardenClientConnection:
        gardenClusterAddress: https://{{ include "garden.domain" .}}
        bootstrapKubeconfig:
          secretRef:
            name: gardenlet-bootstrap-kubeconfig
            namespace: garden
        kubeconfigSecret:
          name: gardenlet-kubeconfig
          namespace: garden
    podLabels:
      networking.resources.gardener.cloud/to-virtual-garden-kube-apiserver-tcp-443: allowed
