---
apiVersion: v1
kind: Secret
metadata:
  name: garden-base-values
  namespace: flux-system
type: Opaque
stringData:
  values.yaml: |-
    runtimeCluster:
      ingress:
        domains:
          - {{ include "garden.ingressDomain" . }}
        controller:
          kind: nginx
      networking:
        nodes: {{ .Values.runtimeCluster.networking.nodes }}
        pods:  {{ .Values.runtimeCluster.networking.pods }}
        services:  {{ .Values.runtimeCluster.networking.services }}
      settings:
        verticalPodAutoscaler:
          enabled: true
        topologyAwareRouting:
          enabled: false
    virtualCluster:
      dns:
        domains:
        - {{ include "api.domain" . }}
      etcd:
        main:
          storage:
            capacity: 25Gi
        events:
          storage:
            capacity: 10Gi
      kubernetes:
        version: 1.26.1
        kubeAPIServer:
          oidcConfig:
  {{ if .Values.issuer.ca }}
            caBundle: |
              {{- .Values.issuer.ca | nindent 14 }}
  {{ end }}
            clientID: kube-kubectl
            groupsClaim: groups
            issuerURL: https://{{ include "identity.domain" . }}/oidc
            usernameClaim: email
      gardener:
        clusterIdentity: {{ .Values.clusterIdentity }}
      maintenance:
        timeWindow:
          begin: 220000+0100
          end: 230000+0100
      networking:
        services: {{ .Values.virtualCluster.networking.services }}
