{{- if or ($.Values.garden).name $.Values.debug }}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: garden-ready
  namespace: {{ $.Release.Namespace }}
spec:
  interval: {{ $.Values.yake.interval }}
  timeout: {{ $.Values.yake.timeout }}
  retryInterval: {{ $.Values.yake.retryInterval }}
  sourceRef:
{{ $.Values.yake.sourceRef | toYaml | indent 4 }}
  path: ./garden-ready
  prune: {{ $.Values.yake.prune }}
  healthChecks:
    - apiVersion: operator.gardener.cloud/v1alpha1
      kind: Garden
      name: {{ ($.Values.garden).name | default "garden" }}
    - apiVersion: v1
      kind: Secret
      name: gardener-internal
      namespace: yake
{{- end }}
