apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-management
  namespace: yake
spec:
  install:
    remediation:
      retries: 3
    createNamespace: true
  interval: 1m
  targetNamespace: garden
  dependsOn:
    - name: cert-management-config
  chart:
    spec:
      chart: cert-management
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: gardener-community-charts
        namespace: yake
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: cert-management-yake-values
      optional: false
    - kind: Secret
      name: cert-management-values
      optional: true
