apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dns-management-config
  namespace: yake
spec:
  install:
    remediation:
      retries: 3
    createNamespace: true
  interval: 1m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: dns-management/config
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: yake
        namespace: yake
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: yake-config
      optional: false
