{{- define "garden.ingressDomain" -}}
{{- (print (first (lookup "operator.gardener.cloud/v1alpha1" "Garden" "" .Values.garden.name).spec.runtimeCluster.ingress.domains)) }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: cert-management-yake-values
  namespace: yake
type: Opaque
stringData:
  values.yaml: |-
{{- if .Values.registryOverwrite }}
    image:
      repository: {{ include "replaceRegistry" (dict "europe-docker.pkg.dev/gardener-project/releases/cert-controller-manager" .Values.registryOverwrite) }}
{{- end }}
    createCRDs:
      issuers: false
      certificates: false
    configuration:
      defaultIssuer: default-issuer
      defaultIssuerDomainRanges: "{{ include "garden.ingressDomain" . }}"
      certClass: base-cert-class
      issuerNamespace: garden
      dnsClass: base-dns-class
      dnsNamespace: garden
