apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: yake-local-config
  namespace: yake
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: yake
    namespace: yake
  path: ./hack/yake-local/config/
  prune: false
