apiVersion: v1
kind: Secret
metadata:
  name: kyverno-yake-values
  namespace: yake
type: Opaque
stringData:
  values.yaml: |
    admissionController:
      replicas: 3
    backgroundController:
      replicas: 2
    cleanupController:
      replicas: 2
    reportsController:
      replicas: 2
