apiVersion: v1
kind: Secret
metadata:
  name: cert-management-values
  namespace: yake
type: Opaque
stringData:
  values.yaml: |
    configuration:
      issuerPrecheckNameservers: kube-dns.kube-system.svc.cluster.local
      precheckNameservers: kube-dns.kube-system.svc.cluster.local
    podLabels:
      networking.resources.gardener.cloud/to-step-certificates-tcp-9000: allowed
