apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gardener-operator
  namespace: yake
spec:
  install:
    remediation:
      retries: 3
    createNamespace: true
  targetNamespace: garden
  interval: 1m
  chart:
    spec:
      chart: gardener-operator
      version: 1.99.1
      sourceRef:
        kind: HelmRepository
        name: gardener-community-charts
        namespace: yake
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: gardener-operator-values
      optional: true
