apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: yake
spec:
  interval: 1m
  targetNamespace: kyverno
  dependsOn:
    - name: kyverno-config
      namespace: yake
  chart:
    spec:
      chart: kyverno
      version: 3.2.6
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: yake
      interval: 1m
  install:
    createNamespace: true
    remediation:
      retries: 10
  valuesFrom:
    - kind: Secret
      name: kyverno-yake-values
      optional: false
    - kind: Secret
      name: kyverno-values
      optional: true
