# imported from https://github.com/23technologies/yake/tree/release-v1.76/helmcharts/gardener-controlplane/charts/application/templates
{{- define "gardener.secret-internal-domain" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: internal-domain-{{ ( required ".internalDomain.domain is required" (replace "." "-" .Values.gardener.internalDomain.domain) ) }}
  namespace: garden
  labels:
    app: gardener
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    gardener.cloud/role: internal-domain
  annotations:
    dns.gardener.cloud/provider: {{ ( required ".internalDomain.provider is required" .Values.gardener.internalDomain.provider ) }}
    dns.gardener.cloud/domain: {{ ( required ".internalDomain.domain is required" .Values.gardener.internalDomain.domain ) }}
    {{- if .Values.gardener.internalDomain.zone }}
    dns.gardener.cloud/zone: {{ .Values.gardener.internalDomain.zone }}
    {{- end }}
type: Opaque
data:
{{ toYaml .Values.gardener.internalDomain.credentials | indent 2 }}
{{- end -}}
{{- include "gardener.secret-internal-domain" . }}
