apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: garden
  namespace: flux-system
spec:
  install:
    remediation:
      retries: 3
    createNamespace: true
  interval: 1m
  dependsOn:
    - name: configuration
  chart:
    spec:
      chart: gardener/garden
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: yake
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: garden-base-values
      optional: false
    - kind: Secret
      name: garden-values-0
      optional: true
    - kind: Secret
      name: garden-values-1
      optional: true
    - kind: Secret
      name: garden-values-2
      optional: true
    - kind: Secret
      name: garden-values
      optional: true
