apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: garden-kubeconfig
  namespace: garden
spec:
  install:
    remediation:
      retries: 3
    createNamespace: true
  interval: 1m
  chart:
    spec:
      chart: gardener/garden-kubeconfig
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: yake
        namespace: flux-system
      interval: 1m
  values:
    output:
      name: gardener-internal
      namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: gardener-internal
      optional: false
      valuesKey: kubeconfig
      targetPath: kubeconfig
