apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificates.yaml
  - cloudprofiles.yaml
  - extensions.yaml
  - garden.yaml
  - gardenlet.yaml
  - garden-content.yaml
  - garden-kubeconfig.yaml
  - identity.yaml
  - networkpolicies
  - priorityclasses.yaml
  - webterminal.yaml
