apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: identity
  namespace: yake
spec:
  install:
    remediation:
      retries: 3
    createNamespace: true
  targetNamespace: garden
  dependsOn:
    - name: identity-config
      namespace: yake
  interval: 1m
  chart:
    spec:
      chart: identity
      version: 3.0.0
      sourceRef:
        kind: HelmRepository
        name: gardener-community-charts
        namespace: yake
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: identity-yake-values
      optional: false
    - kind: Secret
      name: identity-values
      optional: true
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              group: apps
              version: v1
              name: identity
              namespace: garden
            patch: |
              - op: add
                path: /spec/template/spec/priorityClassName
                value: identity
          - target:
              kind: Ingress
              group: networking.k8s.io
              version: v1
              name: identity-ingress
              namespace: garden
            patch: |
              - op: add
                path: /spec/ingressClassName
                value: nginx-ingress-gardener
