apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-wildcard
  namespace: yake
spec:
  install:
    remediation:
      retries: 3
    createNamespace: true
  targetNamespace: garden
  interval: 1m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: cert-wildcard/chart
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: yake
        namespace: yake
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: cert-wildcard-values
      optional: true
